version: '3.8'

services:
  db:
    image: postgres:16
    container_name: coffee_machine_db
    environment:
      POSTGRES_DB: coffee_machine
      POSTGRES_USER: coffee_admin
      POSTGRES_PASSWORD: coffeeForever9605
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 